### ISSUE TITLE
测试问题记录

### ISSUE THREAD

**Issue by hobo0cn** [hobo0cn/U-GIS-front#1]
**测试问题记录**

**Comment by junfengyuan** [comment]
退出登录，没有返回到系统登录页面。

已修改（By Halbert）

**Comment by hobo0cn** [comment]
收到

**Comment by junfengyuan** [comment]
标题样式不对
![111](https://cloud.githubusercontent.com/assets/23006630/19624693/3bbe018a-9935-11e6-855e-f26b19011a93.JPG)

小安已经修改

**Comment by junfengyuan** [comment]
缺少测试数据，无法测试
已经添加测试数据（By Halert）

**Comment by junfengyuan** [comment]
业主主页，缺搜索功能

已经增加（By Halbert）

**Comment by junfengyuan** [comment]
微软Edge浏览器系统名称样式乱：
![909](https://cloud.githubusercontent.com/assets/23006630/19624841/5f1dfec8-993a-11e6-9b90-df8c08ba75d5.JPG)

（小安已经修改）

**Comment by junfengyuan** [comment]
忘记密码后，重置密码不成功。

--已经修改（By Halbert）
